# Generated by Django 5.1.1 on 2024-12-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="room_background",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
