# Generated by Django 5.1.1 on 2024-12-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_post2_profile_post3"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.TextField(blank=True, null=True),
        ),
    ]
