# Generated by Django 5.1.1 on 2024-12-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_room_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="room_background",
            field=models.CharField(
                blank=True, default="#a8c7ff", max_length=7, null=True
            ),
        ),
    ]
