# Generated by Django 5.1.1 on 2024-12-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="link1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="link2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="link3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="link4",
            field=models.TextField(blank=True, null=True),
        ),
    ]
